all: 
	gcc -Wall -pthread demo_app.c -o demo_app

clean:
	rm demo_app

help:
	@echo ""
	@echo "make all     -> builds demo application"
	@echo "make clean   -> delete build artifacts"
	@echo ""

TEST_HW_PLATFORM := ”HOST”
